project_id = "udbcfwtgniqbupgeodga"

[functions.create-empresa]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.invite-user-to-empresa]
verify_jwt = false

[functions.generate-saas-invoice-pdf]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false